/*
Navicat MySQL Data Transfer

Source Server         : localhost_3306
Source Server Version : 50617
Source Host           : localhost:3306
Source Database       : midterm-date-picker

Target Server Type    : MYSQL
Target Server Version : 50617
File Encoding         : 65001

Date: 2016-04-08 20:30:13
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for sport_dob
-- ----------------------------
DROP TABLE IF EXISTS `sport_dob`;
CREATE TABLE `sport_dob` (
  `spec_id` int(11) NOT NULL AUTO_INCREMENT,
  `spec_name` varchar(255) DEFAULT NULL,
  `spec_content` text,
  `spec_img` varchar(255) DEFAULT NULL,
  `spec_type` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`spec_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of sport_dob
-- ----------------------------
INSERT INTO `sport_dob` VALUES ('1', 'Magic Johnson', 'Earvin \"Magic\" Johnson Jr. (born August 14, 1959) is a retired American professional basketball player who played point guard for the Los Angeles Lakers of the National Basketball Association (NBA) for 13 seasons. After winning championships in high school and college, Johnson was selected first overall in the 1979 NBA draft by the Lakers. He won a championship and an NBA Finals Most Valuable Player Award in his rookie season, and won four more championships with the Lakers during the 1980s. Johnson retired abruptly in 1991 after announcing that he had contracted HIV, but returned to play in the 1992 All-Star Game, winning the All-Star MVP Award. After protests from his fellow players, he retired again for four years, but returned in 1996, at age 36, to play 32 games for the Lakers before retiring for the third and final time.\r\nJohnson\'s career achievements include three NBA MVP Awards, nine NBA Finals appearances, twelve All-Star games, and ten All-NBA First and Second Team nominations. He led the league in regular-season assists four times, and is the NBA\'s all-time leader in average assists per game, at 11.2. Johnson was a member of the 1992 United States men\'s Olympic basketball team (\"The Dream Team\"), which won the Olympic gold medal in 1992. After leaving the NBA in 1992, Johnson formed the Magic Johnson All-Stars, a barnstorming team that travelled around the world playing exhibition games. Johnson was honored as one of the 50 Greatest Players in NBA History in 1996.\r\n', 'images/magic.jpg', 'B');
INSERT INTO `sport_dob` VALUES ('2', 'Randy Moss', '\r\nRandy Gene Moss (born February 13, 1977) is a former American football wide receiver who played 14 seasons in the National Football League (NFL). He holds the NFL single-season touchdown reception record (23 in 2007), the NFL single-season touchdown reception record for a rookie (17 in 1998), and is second on the NFL all-time regular season touchdown reception list with 156. He is widely considered among the greatest wide receivers of all time.</br>\r\nMoss played college football for Marshall University, and twice earned All-America honors. He was drafted by the Minnesota Vikings in the first round of the 1998 NFL Draft, where he played for seven years before a trade in 2005 brought him to the Oakland Raiders. On April 29, 2007, Moss was traded to the New England Patriots for a fourth-round draft pick. On October 6, 2010, Moss returned to the Vikings in a trade from the Patriots. However, his stint in Minnesota was short-lived, as he was waived by the team less than a month later, and claimed by the Tennessee Titans. After sitting out the 2011 season, Moss signed a one-year contract with the 49ers for the 2012 season then opted to retire prior to the 2013 season.\r\n', 'images/randy-515px.jpg', 'X');
INSERT INTO `sport_dob` VALUES ('3', 'Kurt Warner', 'Kurtis Eugene \"Kurt\" Warner (born June 22, 1971) is a former American football quarterback, a current part-time TV football analyst, and a philanthropist. He played for three National Football League teams: the St. Louis Rams, the New York Giants, and the Arizona Cardinals. He was originally signed by the Green Bay Packers as an undrafted free agent in 1994 after playing college football at Northern Iowa. Warner went on to be considered the best undrafted NFL player of all time, following a 12-year career regarded as one of the greatest stories in NFL history.\r\nWarner first attained stardom while playing for the St. Louis Rams from 1998 to 2003, where he won two NFL MVP awards in 1999 and 2001 as well as the Super Bowl MVP award in Super Bowl XXXIV. He led the 2008 Arizona Cardinals to Super Bowl XLIII (the franchise\'s first Super Bowl berth), and owns the three highest single-game passing yardage totals in Super Bowl history. Warner currently holds the seventh-highest career passer rating of all-time (93.7), and the third-highest career completion percentage in NFL history with 65.5%.\r\nIn 13 career playoff games, Warner ranks first all-time in completion percentage (66.5%), first in yards per attempt (8.55), and second in passer rating (102.8). He announced his retirement on January 29, 2010.\r\n', 'images/kurt-575px.jpg', 'X');
INSERT INTO `sport_dob` VALUES ('4', 'Michael Jordan', 'Michael Jeffrey Jordan (born February 17, 1963), also known by his initials, MJ, is an American former professional basketball player. He is also a businessman, and principal owner and chairman of the Charlotte Hornets. Jordan played 15 seasons in the National Basketball Association (NBA) for the Chicago Bulls and Washington Wizards. His biography on the NBA website states: \"By acclamation, Michael Jordan is the greatest basketball player of all time.\" Jordan was one of the most effectively marketed athletes of his generation and was considered instrumental in popularizing the NBA around the world in the 1980s and 1990s.\r\nJordan played three seasons for coach Dean Smith at the University of North Carolina. He was a member of the Tar Heels\' national championship team in 1982. Jordan joined the NBA\'s Chicago Bulls in 1984 as the third overall draft pick. He quickly emerged as a league star, entertaining crowds with his prolific scoring. His leaping ability, illustrated by performing slam dunks from the free throw line in slam dunk contests, earned him the nicknames \"Air Jordan\" and \"His Airness\". He also gained a reputation for being one of the best defensive players in basketball. In 1991, he won his first NBA championship with the Bulls, and followed that achievement with titles in 1992 and 1993, securing a \"three-peat\". Although Jordan abruptly retired from basketball before the beginning of the 1993-94 NBA season to pursue a career in baseball, he returned to the Bulls in March 1995 and led them to three additional championships in 1996, 1997, and 1998, as well as an NBA-record 72 regular-season wins in the 1995-96 NBA season. Jordan retired for a second time in January 1999, but returned for two more NBA seasons from 2001 to 2003 as a member of the Wizards.\r\n', 'images/jordan.jpg', 'B');
INSERT INTO `sport_dob` VALUES ('5', 'Larry Fitzgerald', 'Larry Darnell Fitzgerald Jr. (born August 31, 1983) is an American football wide receiver for the Arizona Cardinals of the National Football League (NFL). He was drafted by the Cardinals third overall in the 2004 NFL Draft. He played college football at Pittsburgh, where he earned unanimous All-American honors.\r\nFitzgerald has been selected for the Pro Bowl nine times, and currently ranks fifth all-time in NFL history in receiving yards per game for a career (76.0 yards per game), behind Calvin Johnson, Andre Johnson, Torry Holt, and Marvin Harrison. On November 24, 2013, at 30 years and 85 days of age, he became the youngest NFL receiver to reach 11,000 career receiving yards, surpassing the previous record-holder, Randy Moss. He agreed to an eight-year, $120 million contract extension on August 20, 2011.\r\n', 'images/larry.jpg', 'Y');
INSERT INTO `sport_dob` VALUES ('6', 'Stephen Curry', 'Wardell Stephen \"Steph\" Curry II (born March 14, 1988) is an American professional basketball player for the Golden State Warriors of the National Basketball Association (NBA). He is considered by many to be the greatest shooter in NBA history. In 2015, Curry won the NBA Most Valuable Player Award and led the Warriors to their first championship since 1975.\r\nCurry is the son of former NBA player Dell and older brother of current NBA player Seth. He played college basketball for Davidson. There, he was twice named Southern Conference Player of the Year and set the all-time scoring record for both Davidson and the Southern Conference. During his sophomore year, he also set the single-season NCAA record for three-pointers made.\r\nCurry was selected with the seventh overall pick in the 2009 NBA draft by the Golden State Warriors. During the 2012-13 season, he set the NBA record for three-pointers made in a regular season with 272. He surpassed that record in 2014-15 with 286, and again in 2015-16 with 382 (ongoing). During the 2013-14 season, he and teammate Klay Thompson were nicknamed the \"Splash Brothers\" en route to setting the NBA record for combined three-pointers in a season with 484, a record they broke in 2014-15 (525) and again in 2015-16 (648, ongoing). A three-time NBA All-Star, Curry holds the league record for most consecutive games with a made three-pointer (with 148).\r\n', 'images/steph.jpg', 'Y');
INSERT INTO `sport_dob` VALUES ('7', 'Joe Namath', 'Joseph William Namath (/ˈneɪmᵻθ/; born May 31, 1943), nicknamed \"Broadway Joe\", is a former American football quarterback and actor. He played college football for the University of Alabama under coach Paul \"Bear\" Bryant from 1962 to 1964, and professional football in the American Football League (AFL) and National Football League (NFL) during the 1960s and 1970s. Namath was an American Football League icon and played for that league\'s New York Jets for most of his professional football career. He finished his career with the NFL\'s Los Angeles Rams. He was elected to the Hall of Fame in 1985.\r\nNamath retired after playing in 143 career games (including playoff games) with 68 wins, 71 losses and 4 ties. In his 132 career starts he was 64-64-4, and he was 4-7 coming off the bench in relief. In his career he threw 173 touchdowns and 220 interceptions, and completed 1,886 passes for 27,663 yards. During his thirteen years in the AFL and NFL he played for three division champions (the 1968 and 1969 AFL East Champion Jets and the 1977 NFC West Champion Rams) and earned one league championship (1968 AFL Championship), and one Super Bowl victory (Super Bowl III).\r\n', 'images/joe-namath.jpg', 'M');
INSERT INTO `sport_dob` VALUES ('8', 'Bill Russell', 'William Felton \"Bill\" Russell (born February 12, 1934) is an American retired professional basketball player. Russell played center for the Boston Celtics of the National Basketball Association (NBA) from 1956 to 1969. A five-time NBA Most Valuable Player and a twelve-time All-Star, he was the centerpiece of the Celtics dynasty, winning eleven NBA championships during his thirteen-year career. Along with Henri Richard of the National Hockey League\'s Montreal Canadiens, Russell holds the record for the most championships won by an athlete in a North American sports league. Before his professional career, Russell led the University of San Francisco to two consecutive NCAA championships (1955, 1956). He also won a gold medal at the 1956 Summer Olympics as captain of the U.S. national basketball team.\r\nRussell is widely considered one of the best players in NBA history. He was listed as between 6 ft 9 in (2.06 m) and 6 ft 10 in (2.08 m), and his shot-blocking and man-to-man defense were major reasons for the Celtics\' success. He also inspired his teammates to elevate their own defensive play. Russell was equally notable for his rebounding abilities. He led the NBA in rebounds four times, had a dozen consecutive seasons of 1,000 or more rebounds, and remains second all-time in both total rebounds and rebounds per game. He is one of just two NBA players (the other being prominent rival Wilt Chamberlain) to have grabbed more than 50 rebounds in a game. Though never the focal point of the Celtics\' offense, Russell also scored 14,522 career points and provided effective passing.\r\n', 'images/bill_russell52.jpg', 'M');
INSERT INTO `sport_dob` VALUES ('9', 'Tim Duncan', 'Timothy Theodore Duncan (born April 25, 1976) is an American professional basketball player who has played his entire career for the San Antonio Spurs of the National Basketball Association (NBA). Widely considered to be the greatest power forward of all-time, he is a five-time NBA champion, two-time NBA MVP, three-time NBA Finals MVP, and NBA Rookie of the Year. He is also a 15-time NBA All-Star and the only player ever to be selected to both the All-NBA and All-Defensive Teams in every one of his first 13 seasons.\r\nDuncan started out as a swimmer and only began playing basketball in ninth grade after Hurricane Hugo destroyed the only Olympic-sized pool on his home of Saint Croix, U.S. Virgin Islands. He soon became a standout for St. Dunstan\'s Episcopal High School, and had an illustrious college career with the Wake Forest University Demon Deacons, winning the Naismith College Player of the Year, USBWA College Player of the Year and John Wooden awards in his final year. Duncan graduated from college before entering the 1997 NBA draft as the number one pick.\r\nOff the court, Duncan is known for his quiet and unassuming ways, as well as his active philanthropy. He holds an honorary degree in psychology and created the Tim Duncan Foundation to raise general health awareness and fund education and youth sports in various parts of the United States.\r\n', 'images/duncan.jpg', 'X');
INSERT INTO `sport_dob` VALUES ('10', 'Jerry Rice', 'Jerry Lee Rice (born October 13, 1962) is a former American football wide receiver who played 20 seasons in the National Football League (NFL). He is widely considered to be the greatest wide receiver in NFL history and among the greatest NFL players overall. On November 4, 2010, Rice was chosen by NFL Network\'s NFL Films production The Top 100: NFL\'s Greatest Players as the greatest player in NFL history.\r\nHe is the all-time leader in most major statistical categories for wide receivers, including receptions, touchdown receptions, and receiving yards, once being the leader for total yards in a season. Rice was selected to the Pro Bowl 13 times (1986-1996, 1998, 2002) and named All-Pro 12 times in his 20 NFL seasons. He won three Super Bowl rings playing for the San Francisco 49ers and an AFC Championship with the Oakland Raiders. As of 2014 Rice holds over 100 NFL records, the most of any player by a wide margin.\r\n', 'images/jerry.jpg', 'B');
INSERT INTO `sport_dob` VALUES ('11', 'Wilt Chamberlain', 'Wilton Norman \"Wilt\" Chamberlain (August 21, 1936 - October 12, 1999) was an American basketball player. He played for the Philadelphia/San Francisco Warriors, the Philadelphia 76ers, and the Los Angeles Lakers of the National Basketball Association (NBA); he played for the University of Kansas and also for the Harlem Globetrotters before playing in the NBA. The 7 foot 1 inch Chamberlain weighed 250 pounds as a rookie before bulking up to 275 and eventually to over 300 pounds with the Lakers. He played the center position and is widely considered one of the greatest and most dominant players in NBA history.', 'images/wilt.jpg', 'M');
INSERT INTO `sport_dob` VALUES ('12', 'Lebron James', 'LeBron Raymone James ( born December 30, 1984) is an American professional basketball player for the Cleveland Cavaliers of the National Basketball Association (NBA). He has started at the small forward and power forward positions. James has won two NBA championships (2012, 2013), four NBA Most Valuable Player Awards (2009, 2010, 2012, 2013), two NBA Finals MVP Awards (2012, 2013), two Olympic gold medals (2008, 2012), an NBA scoring title (2008), and the NBA Rookie of the Year Award (2004). He has also been selected to 12 NBA All-Star teams, 11 All-NBA teams, and six All-Defensive teams, and is the Cavaliers\' all-time leading scorer.\r\nJames played high school basketball at St. Vincent - St. Mary High School in his hometown of Akron, Ohio, where he was highly promoted in the national media as a future NBA superstar. After graduating, he was selected with the first overall pick in the 2003 NBA draft by the Cavaliers. James led Cleveland to the franchise\'s first Finals appearance in 2007, losing to the San Antonio Spurs. In 2010, he left the Cavaliers for the Miami Heat in a highly publicized ESPN special titled The Decision. James played four seasons for the Heat, reaching the Finals all four years and winning back-to-back championships in 2012 and 2013. In 2013, he led Miami on a 27-game winning streak, the third longest in league history. Following his final season with the Heat, James opted out of his contract and re-joined the Cavaliers. Behind his leadership, Cleveland advanced to the Finals before losing to the Golden State Warriors.\r\n', 'images/lebron.jpg', 'Y');
